# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amock < Formula
  desc "A simple mock server for REST APIs."
  homepage "https://github.com/matronator/amock"
  version "0.1.13"
  license "GPL-3.0-only"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matronator/amock/releases/download/v0.1.13/amock_Darwin_x86_64.tar.gz"
      sha256 "f285afc32bb99111499a9e038eb62e0037e872a89ee9c745379ba17cb7d05729"

      def install
        bin.install "amock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matronator/amock/releases/download/v0.1.13/amock_Darwin_arm64.tar.gz"
      sha256 "a176da387deb77e732da80f57b400a46b426c8dce253f5e9cfe8db39de113540"

      def install
        bin.install "amock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/matronator/amock/releases/download/v0.1.13/amock_Linux_x86_64.tar.gz"
      sha256 "4c4af787750cfd5f6407036e45d5b6e15b2181b7fb8796f22ff540b35da58362"

      def install
        bin.install "amock"
      end
    end
  end
end
