# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amock < Formula
  desc "A simple mock server for REST APIs."
  homepage "https://github.com/matronator/amock"
  version "0.1.2"
  license "MIT"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matronator/amock/releases/download/v0.1.2/amock_Darwin_x86_64.tar.gz"
      sha256 "f4f950995563d22ce98754b5237dc4043cf80c3c150d16fded30eaca5490032a"

      def install
        bin.install "amock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matronator/amock/releases/download/v0.1.2/amock_Darwin_arm64.tar.gz"
      sha256 "8c310d787c5e8590902c613efc3b13957e5c2239c4eb57e457841a6d3a869da9"

      def install
        bin.install "amock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/matronator/amock/releases/download/v0.1.2/amock_Linux_x86_64.tar.gz"
      sha256 "f7c1a14ce068eddff9ec547f44091d8e2c9c51d7b513a23fe175fe6cda79ea21"

      def install
        bin.install "amock"
      end
    end
  end
end
