# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amock < Formula
  desc "A simple mock server for REST APIs."
  homepage "https://github.com/matronator/amock"
  version "0.1.6"
  license "GPL-3.0-only"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matronator/amock/releases/download/v0.1.6/amock_Darwin_x86_64.tar.gz"
      sha256 "e2b143d310c5ad76e4b5848e8133e5817ea37e66a3159595dc9386e7c41d3a5b"

      def install
        bin.install "amock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matronator/amock/releases/download/v0.1.6/amock_Darwin_arm64.tar.gz"
      sha256 "be20e26b589200f3f500561c59baf5f749d457c2767c6a1c3b758e6c11641cfa"

      def install
        bin.install "amock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/matronator/amock/releases/download/v0.1.6/amock_Linux_x86_64.tar.gz"
      sha256 "b007dc69cd93c3fa82e49a2edbfbacd1c64568ddaa435c2b7847abff9107b8b5"

      def install
        bin.install "amock"
      end
    end
  end
end
